version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=DB_SistemaContatos;Integrated Security=True;
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    network_mode: "host"
    environment:
      - ACCEPT_EULA=Y
    command: ["sqlservr", "--memory=1g"] 
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
